import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar";
import { LeftSidebar } from "@/components/navigation-sidebar/left-sidebar";
import { UserProvider } from "@/hooks/userContext";
import { Providers } from "./providers";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "TESTAPP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${poppins.variable}`}>
        <SidebarProvider>
          <UserProvider>
            <LeftSidebar />
            <Providers>{children}</Providers>
          </UserProvider>
        </SidebarProvider>
      </body>
    </html>
  );
}
